Compute numpy dtype
midstar/pycstruct pull request #24
Opened 2021-02-15 22:14 UTC by vallsv

This PR introduce a `dtype` method for definition classes.

This can be used with numpy to parse a bytes structure.

This can be used the following way:
```
import pycstruct
import numpy

rgba_t = pycstruct.StructDef()
rgba_t.add("uint8", "r")
rgba_t.add("uint8", "g")
rgba_t.add("uint8", "b")
rgba_t.add("uint8", "a")

data = b'\x01\x02\x03\x00'
rgba = numpy.frombuffer(data, dtype=type_t.dtype())
```

There is some limitations:
- No bitfields
- No unions
- No string decoding (everything is bytes)
- The result have to be handled in different way sometimes

2021-02-21 07:41 UTC, midstar commented on pycstruct/pycstruct.py
> +  def dtype(self):
Could you add some comments for this method. I would like the comment to include:

- What it does (i.e. used for serialization/deserialization using numpy structured arrays)
- Why to use it (I guess performance is the main reason)
- Limitations (Nested structs, enums etc)
- Some examples on how to use it

You can check that the documentation looks ok by entering the doc directory and write "make html".

2021-02-21 07:41 UTC, midstar requested changes
Check my comment regarding documentation. Also, it seems to be a merge conflict right now.

2021-02-22 22:41 UTC, vallsv commented
Wow you did a lot of work this days.

I did rebase changes + some documentation.

Let me know if it is enough.

2021-02-22 23:04 UTC, vallsv commented
I feel like pylint is a bit too strong. I have no idea what it complains about.

2021-02-22 23:12 UTC, vallsv commented
I did found the problem, but it sounds weird.

2021-02-24 20:33 UTC, midstar approved these changes

2021-02-24 20:33 UTC, merged